name: Fookedonhonix
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#52534b'
    - '#fffdfe'
    - '#010600'
    - '#c1c5c8'
    - '#af7d74'
  brandStrength: 0.875
  lightness: 0.28566369134932756
  saturation: 0.12082755588926375
  rhythmicContrast: 0.8069297869224101
purpose: []
